import type { Language } from "@falkenslab/agent-kit";

// Los textos de su página, en cada idioma del kit (los del chat los da el kit en el estado: las
// etiquetas de las herramientas, los avisos). Las sugerencias se mandan tal cual al capitán.

const TEXTS = {
  en: {
    tagline: "Retired pirate cat · jokes, lore and a logbook",
    welcomeTitle: "Ahoy, shipmate!",
    welcomeText: "I tell jokes, learn from the documents in my treasure chest and keep what I learn in my logbook. Pick a mission or write your own.",
    suggestions: [
      { icon: "🦜", label: "Tell me a joke", prompt: "Tell me a joke" },
      { icon: "🗺️", label: "Learn from the chest", prompt: "/captain-whiskers:learn" },
      { icon: "🕰️", label: "How long until Talk Like a Pirate Day?", prompt: "How many days until Talk Like a Pirate Day?" },
      { icon: "🧭", label: "What can you do?", prompt: "What can you do, and how do I use you?" },
    ],
    placeholder: "Write to the captain…",
    hint: "Enter to send · Shift+Enter for a new line",
    send: "Send",
    stop: "Stop",
    working: "Working",
    you: "You",
    mode: "Mode",
    modes: { guided: "Guided", interactive: "Interactive", plan: "Plan", autonomous: "Autonomous" },
    modeHelp: {
      guided: "Asks you when it needs to",
      interactive: "Asks before every action",
      plan: "Only reads and plans",
      autonomous: "Asks nothing",
    },
    newConversation: "New conversation",
    conversations: "Conversations",
    current: "current",
    noRuns: "No earlier conversations yet.",
    extensions: "Extensions",
    active: "Active",
    inactive: "Not available",
    disabled: "Installed, turned off",
    turnOn: "Turn on",
    turnOff: "Turn off",
    provides: "Provides",
    builtIn: "built-in",
    close: "Close",
    approve: "Yes, go ahead",
    reject: "No",
    stopAll: "Stop the turn",
    done: "Done",
    other: "Other: write your own answer",
    answer: "Answer",
    cancel: "Cancel",
    attach: "Choose a file…",
    uploading: "Uploading…",
    uploaded: "Ready to send",
    signInTitle: "Sign in to set sail",
    signInText: "The captain needs a Claude key: an API key (sk-ant-api…) or a token from `claude setup-token` (sk-ant-oat…). It's kept on this computer only.",
    signInPlaceholder: "Paste your key",
    signIn: "Sign in",
    invalidKey: "That doesn't look like a Claude key.",
    replaced: "This conversation is open in another window.",
    useHere: "Use it here",
    disconnected: "Connection lost, reconnecting…",
    online: "Connected",
    busyTurn: "Wait for the captain to finish, or stop him.",
    copy: "Copy",
    copied: "Copied",
    tools: (n: number) => (n === 1 ? "1 action" : `${n} actions`),
    seconds: (s: number) => `${s} s`,
    context: "Context",
    jump: "Latest",
    plan: "Plan",
    question: "The captain asks",
    approval: "Approval needed",
    manual: "Your turn",
  },
  es: {
    tagline: "Gato pirata retirado · chistes, saber y un cuaderno",
    welcomeTitle: "¡Ahoy, grumete!",
    welcomeText: "Cuento chistes, aprendo de los documentos de mi cofre y apunto lo que aprendo en mi cuaderno de bitácora. Elige una misión o escribe la tuya.",
    suggestions: [
      { icon: "🦜", label: "Cuéntame un chiste", prompt: "Cuéntame un chiste" },
      { icon: "🗺️", label: "Aprende del cofre", prompt: "/captain-whiskers:learn" },
      { icon: "🕰️", label: "¿Cuánto falta para el Día de Hablar como un Pirata?", prompt: "¿Cuántos días faltan para el Día Internacional de Hablar como un Pirata?" },
      { icon: "🧭", label: "¿Qué sabes hacer?", prompt: "¿Qué sabes hacer y cómo te uso?" },
    ],
    placeholder: "Escribe al capitán…",
    hint: "Intro para enviar · Mayús+Intro para otra línea",
    send: "Enviar",
    stop: "Parar",
    working: "Trabajando",
    you: "Tú",
    mode: "Modo",
    modes: { guided: "Guiado", interactive: "Interactivo", plan: "Plan", autonomous: "Autónomo" },
    modeHelp: {
      guided: "Te pregunta cuando lo necesita",
      interactive: "Pregunta antes de cada acción",
      plan: "Solo lee y planifica",
      autonomous: "No pregunta nada",
    },
    newConversation: "Nueva conversación",
    conversations: "Conversaciones",
    current: "actual",
    noRuns: "Aún no hay conversaciones anteriores.",
    extensions: "Extensiones",
    active: "Activas",
    inactive: "No disponibles",
    disabled: "Instaladas, apagadas",
    turnOn: "Activar",
    turnOff: "Desactivar",
    provides: "Aporta",
    builtIn: "integrada",
    close: "Cerrar",
    approve: "Sí, adelante",
    reject: "No",
    stopAll: "Parar el turno",
    done: "Hecho",
    other: "Otra: escribe tu respuesta",
    answer: "Responder",
    cancel: "Cancelar",
    attach: "Elegir un fichero…",
    uploading: "Subiendo…",
    uploaded: "Listo para enviar",
    signInTitle: "Inicia sesión para zarpar",
    signInText: "El capitán necesita una clave de Claude: una API key (sk-ant-api…) o un token de `claude setup-token` (sk-ant-oat…). Se guarda solo en este ordenador.",
    signInPlaceholder: "Pega tu clave",
    signIn: "Entrar",
    invalidKey: "Eso no parece una clave de Claude.",
    replaced: "Esta conversación está abierta en otra ventana.",
    useHere: "Usarla aquí",
    disconnected: "Se perdió la conexión, reconectando…",
    online: "Conectado",
    busyTurn: "Espera a que el capitán termine, o páralo.",
    copy: "Copiar",
    copied: "Copiado",
    tools: (n: number) => (n === 1 ? "1 acción" : `${n} acciones`),
    seconds: (s: number) => `${s} s`,
    context: "Contexto",
    jump: "Lo último",
    plan: "Plan",
    question: "El capitán pregunta",
    approval: "Hace falta tu permiso",
    manual: "Te toca",
  },
  fr: {
    tagline: "Chat pirate à la retraite · blagues, savoir et un journal",
    welcomeTitle: "Ohé, matelot !",
    welcomeText: "Je raconte des blagues, j'apprends des documents de mon coffre et je note ce que j'apprends dans mon journal de bord. Choisis une mission ou écris la tienne.",
    suggestions: [
      { icon: "🦜", label: "Raconte-moi une blague", prompt: "Raconte-moi une blague" },
      { icon: "🗺️", label: "Apprends du coffre", prompt: "/captain-whiskers:learn" },
      { icon: "🕰️", label: "Combien de jours avant la Journée du parler pirate ?", prompt: "Combien de jours avant la Journée internationale du parler pirate ?" },
      { icon: "🧭", label: "Que sais-tu faire ?", prompt: "Que sais-tu faire, et comment t'utiliser ?" },
    ],
    placeholder: "Écris au capitaine…",
    hint: "Entrée pour envoyer · Maj+Entrée pour une nouvelle ligne",
    send: "Envoyer",
    stop: "Arrêter",
    working: "Au travail",
    you: "Toi",
    mode: "Mode",
    modes: { guided: "Guidé", interactive: "Interactif", plan: "Plan", autonomous: "Autonome" },
    modeHelp: {
      guided: "Te demande quand il en a besoin",
      interactive: "Demande avant chaque action",
      plan: "Lit et planifie seulement",
      autonomous: "Ne demande rien",
    },
    newConversation: "Nouvelle conversation",
    conversations: "Conversations",
    current: "actuelle",
    noRuns: "Pas encore de conversations précédentes.",
    extensions: "Extensions",
    active: "Actives",
    inactive: "Indisponibles",
    disabled: "Installées, éteintes",
    turnOn: "Activer",
    turnOff: "Désactiver",
    provides: "Apporte",
    builtIn: "intégrée",
    close: "Fermer",
    approve: "Oui, vas-y",
    reject: "Non",
    stopAll: "Arrêter le tour",
    done: "Fait",
    other: "Autre : écris ta réponse",
    answer: "Répondre",
    cancel: "Annuler",
    attach: "Choisir un fichier…",
    uploading: "Envoi…",
    uploaded: "Prêt à envoyer",
    signInTitle: "Connecte-toi pour lever l'ancre",
    signInText: "Le capitaine a besoin d'une clé Claude : une clé d'API (sk-ant-api…) ou un jeton de `claude setup-token` (sk-ant-oat…). Elle reste sur cet ordinateur.",
    signInPlaceholder: "Colle ta clé",
    signIn: "Se connecter",
    invalidKey: "Ça ne ressemble pas à une clé Claude.",
    replaced: "Cette conversation est ouverte dans une autre fenêtre.",
    useHere: "L'utiliser ici",
    disconnected: "Connexion perdue, reconnexion…",
    online: "Connecté",
    busyTurn: "Attends que le capitaine ait fini, ou arrête-le.",
    copy: "Copier",
    copied: "Copié",
    tools: (n: number) => (n === 1 ? "1 action" : `${n} actions`),
    seconds: (s: number) => `${s} s`,
    context: "Contexte",
    jump: "Le plus récent",
    plan: "Plan",
    question: "Le capitaine demande",
    approval: "Ton accord est nécessaire",
    manual: "À toi",
  },
  de: {
    tagline: "Pirat im Ruhestand · Witze, Wissen und ein Logbuch",
    welcomeTitle: "Ahoi, Matrose!",
    welcomeText: "Ich erzähle Witze, lerne aus den Dokumenten in meiner Schatzkiste und notiere, was ich lerne, in meinem Logbuch. Wähle eine Mission oder schreib deine eigene.",
    suggestions: [
      { icon: "🦜", label: "Erzähl mir einen Witz", prompt: "Erzähl mir einen Witz" },
      { icon: "🗺️", label: "Lerne aus der Kiste", prompt: "/captain-whiskers:learn" },
      { icon: "🕰️", label: "Wie lange noch bis zum Sprich-wie-ein-Pirat-Tag?", prompt: "Wie viele Tage noch bis zum Internationalen Sprich-wie-ein-Pirat-Tag?" },
      { icon: "🧭", label: "Was kannst du?", prompt: "Was kannst du, und wie benutze ich dich?" },
    ],
    placeholder: "Schreib dem Käpt'n…",
    hint: "Enter zum Senden · Umschalt+Enter für eine neue Zeile",
    send: "Senden",
    stop: "Stopp",
    working: "Bei der Arbeit",
    you: "Du",
    mode: "Modus",
    modes: { guided: "Geführt", interactive: "Interaktiv", plan: "Plan", autonomous: "Autonom" },
    modeHelp: {
      guided: "Fragt dich, wenn nötig",
      interactive: "Fragt vor jeder Aktion",
      plan: "Liest und plant nur",
      autonomous: "Fragt nichts",
    },
    newConversation: "Neues Gespräch",
    conversations: "Gespräche",
    current: "aktuell",
    noRuns: "Noch keine früheren Gespräche.",
    extensions: "Erweiterungen",
    active: "Aktiv",
    inactive: "Nicht verfügbar",
    disabled: "Installiert, ausgeschaltet",
    turnOn: "Einschalten",
    turnOff: "Ausschalten",
    provides: "Bringt",
    builtIn: "eingebaut",
    close: "Schließen",
    approve: "Ja, los",
    reject: "Nein",
    stopAll: "Runde abbrechen",
    done: "Erledigt",
    other: "Andere: schreib deine Antwort",
    answer: "Antworten",
    cancel: "Abbrechen",
    attach: "Datei wählen…",
    uploading: "Wird hochgeladen…",
    uploaded: "Bereit zum Senden",
    signInTitle: "Anmelden und Segel setzen",
    signInText: "Der Käpt'n braucht einen Claude-Schlüssel: einen API-Schlüssel (sk-ant-api…) oder ein Token von `claude setup-token` (sk-ant-oat…). Er bleibt auf diesem Rechner.",
    signInPlaceholder: "Schlüssel einfügen",
    signIn: "Anmelden",
    invalidKey: "Das sieht nicht nach einem Claude-Schlüssel aus.",
    replaced: "Dieses Gespräch ist in einem anderen Fenster geöffnet.",
    useHere: "Hier verwenden",
    disconnected: "Verbindung verloren, neuer Versuch…",
    online: "Verbunden",
    busyTurn: "Warte, bis der Käpt'n fertig ist, oder stoppe ihn.",
    copy: "Kopieren",
    copied: "Kopiert",
    tools: (n: number) => (n === 1 ? "1 Aktion" : `${n} Aktionen`),
    seconds: (s: number) => `${s} s`,
    context: "Kontext",
    jump: "Neueste",
    plan: "Plan",
    question: "Der Käpt'n fragt",
    approval: "Deine Zustimmung ist nötig",
    manual: "Du bist dran",
  },
};

type PageTexts = (typeof TEXTS)["en"];

/** Los textos de la página en `language`, listos para JSON: las funciones, como plantillas con {n}. */
export function pageTexts(language: Language): Record<string, unknown> {
  const texts: PageTexts = TEXTS[language];
  return { ...texts, tools: [texts.tools(1), texts.tools(2).replace("2", "{n}")], seconds: texts.seconds(0).replace("0", "{n}") };
}
