import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// The API reference sidebar is generated by TypeDoc (docusaurus-plugin-typedoc) on every build.
// eslint-disable-next-line @typescript-eslint/no-require-imports
const apiSidebar = require("./content/api/typedoc-sidebar.cjs");

const sidebars: SidebarsConfig = {
  guides: [
    "intro",
    {
      type: "category",
      label: "Getting started",
      collapsed: false,
      items: [
        "getting-started/installation",
        "getting-started/authentication",
        "getting-started/first-agent",
        "getting-started/project-layout",
      ],
    },
    {
      type: "category",
      label: "Core concepts",
      collapsed: false,
      items: [
        "core-concepts/architecture",
        "core-concepts/agent-spec",
        "core-concepts/session-config",
        "core-concepts/modes",
        "core-concepts/session-options",
      ],
    },
    {
      type: "category",
      label: "Capabilities",
      items: [
        "capabilities/tools-and-mcp",
        "capabilities/skills-and-plugins",
        "capabilities/subagents",
        "capabilities/knowledge-base",
        "capabilities/knowledge-store",
        "capabilities/prompts",
      ],
    },
    {
      type: "category",
      label: "Human in the loop",
      items: [
        "human-in-the-loop/overview",
        "human-in-the-loop/step-gate",
        "human-in-the-loop/approvals",
        "human-in-the-loop/choices-and-plans",
        "human-in-the-loop/manual-intervention",
        "human-in-the-loop/response-file",
        "human-in-the-loop/interaction-port",
      ],
    },
    {
      type: "category",
      label: "Security",
      items: ["security/overview", "security/file-scope", "security/subagent-gates", "security/permissions-and-isolation", "security/transcript"],
    },
    {
      type: "category",
      label: "Terminal UI",
      items: [
        "terminal-ui/ink-chat",
        "terminal-ui/plain-chat",
        "terminal-ui/progress-view",
        "terminal-ui/wizard",
        "terminal-ui/tool-labels",
        "terminal-ui/themes",
      ],
    },
    {
      type: "category",
      label: "Sessions",
      items: ["sessions/runs-and-resuming", "sessions/languages", "sessions/context-and-cost"],
    },
    {
      type: "category",
      label: "Advanced",
      items: ["advanced/events", "advanced/one-shot-runs", "advanced/custom-hosts", "advanced/hooks"],
    },
    {
      type: "category",
      label: "Examples",
      items: ["examples/captain-whiskers", "examples/recipes"],
    },
    {
      type: "category",
      label: "Reference",
      items: ["reference/sdk-behaviors", "reference/troubleshooting", "reference/versioning"],
    },
  ],
  api: [{ type: "doc", id: "api/index", label: "Overview" }, ...apiSidebar],
};

export default sidebars;
